export default [
  {
    dates: {
      maximum: "2024-08-07",
      minimum: "2024-06-26",
    },
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/lXJ9BtyseV8nHulgUPGkj1cLKw4.jpg",
        genre_ids: [28, 35, 878],
        id: 533535,
        original_language: "en",
        original_title: "Deadpool & Wolverine",
        overview:
          "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        popularity: 19813.958,
        poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        release_date: "2024-07-24",
        title: "Deadpool & Wolverine",
        video: false,
        vote_average: 7.977,
        vote_count: 1074,
      },
      {
        adult: false,
        backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
        genre_ids: [16, 10751, 12, 35],
        id: 1022789,
        original_language: "en",
        original_title: "Inside Out 2",
        overview:
          "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        popularity: 3367.586,
        poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        release_date: "2024-06-11",
        title: "Inside Out 2",
        video: false,
        vote_average: 7.637,
        vote_count: 2200,
      },
      {
        adult: false,
        backdrop_path: "/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg",
        genre_ids: [16, 10751, 35, 28],
        id: 519182,
        original_language: "en",
        original_title: "Despicable Me 4",
        overview:
          "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        popularity: 2714.677,
        poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        release_date: "2024-06-20",
        title: "Despicable Me 4",
        video: false,
        vote_average: 7.2,
        vote_count: 485,
      },
      {
        adult: false,
        backdrop_path: "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
        genre_ids: [27, 878, 53],
        id: 762441,
        original_language: "en",
        original_title: "A Quiet Place: Day One",
        overview:
          "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
        popularity: 2659.712,
        poster_path: "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
        release_date: "2024-06-26",
        title: "A Quiet Place: Day One",
        video: false,
        vote_average: 7.017,
        vote_count: 786,
      },
      {
        adult: false,
        backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
        genre_ids: [16, 35, 10751, 12],
        id: 748783,
        original_language: "en",
        original_title: "The Garfield Movie",
        overview:
          "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
        popularity: 1247.665,
        poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
        release_date: "2024-04-30",
        title: "The Garfield Movie",
        video: false,
        vote_average: 7.218,
        vote_count: 638,
      },
      {
        adult: false,
        backdrop_path: "/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg",
        genre_ids: [16, 878, 28],
        id: 1209290,
        original_language: "en",
        original_title: "Justice League: Crisis on Infinite Earths Part Three",
        overview:
          "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?",
        popularity: 1070.36,
        poster_path: "/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
        release_date: "2024-07-16",
        title: "Justice League: Crisis on Infinite Earths Part Three",
        video: false,
        vote_average: 7.7,
        vote_count: 112,
      },
      {
        adult: false,
        backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
        genre_ids: [28, 35],
        id: 1048241,
        original_language: "en",
        original_title: "My Spy The Eternal City",
        overview:
          "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
        popularity: 949.026,
        poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
        release_date: "2024-07-18",
        title: "My Spy The Eternal City",
        video: false,
        vote_average: 6.735,
        vote_count: 172,
      },
      {
        adult: false,
        backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
        genre_ids: [14, 12, 10751, 35],
        id: 974262,
        original_language: "en",
        original_title: "Descendants: The Rise of Red",
        overview:
          "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
        popularity: 894.147,
        poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
        release_date: "2024-07-11",
        title: "Descendants: The Rise of Red",
        video: false,
        vote_average: 7.023,
        vote_count: 215,
      },
      {
        adult: false,
        backdrop_path: "/59AJ2w9tKRSbBpnxKfB5UyIg6Jf.jpg",
        genre_ids: [27, 53],
        id: 1010600,
        original_language: "en",
        original_title: "The Strangers: Chapter 1",
        overview:
          "After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.",
        popularity: 568.549,
        poster_path: "/cdFZoQDxLRRWXLB3kxCnc674dBF.jpg",
        release_date: "2024-05-15",
        title: "The Strangers: Chapter 1",
        video: false,
        vote_average: 5.996,
        vote_count: 242,
      },
      {
        adult: false,
        backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
        genre_ids: [27, 53],
        id: 646683,
        original_language: "en",
        original_title: "The Exorcism",
        overview:
          "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
        popularity: 602.735,
        poster_path: "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
        release_date: "2024-05-30",
        title: "The Exorcism",
        video: false,
        vote_average: 4.575,
        vote_count: 93,
      },
      {
        adult: false,
        backdrop_path: "/tqSg1hHiSWhHAhnjDhhevaFGsP0.jpg",
        genre_ids: [28, 18],
        id: 1066262,
        original_language: "en",
        original_title: "The Convert",
        overview:
          "Munro, a soldier turned lay preacher, comes to New Zealand to minister to the first British colonists, but he is converted by the powerful chief Maianui to serve a different purpose.",
        popularity: 766.223,
        poster_path: "/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg",
        release_date: "2024-03-14",
        title: "The Convert",
        video: false,
        vote_average: 6.2,
        vote_count: 23,
      },
      {
        adult: false,
        backdrop_path: "/w22yUH5pAZ3CcTjbw9GEzPd5wxs.jpg",
        genre_ids: [878, 35],
        id: 1242372,
        original_language: "zh",
        original_title: "从21世纪安全撤离",
        overview:
          'On Planet K, unknown to anyone on Earth, three teenagers chosen by fate can travel back and forth twenty years into the future by sneezing. In the face of a shocking plot to destroy the world, they have nothing but crystal-clear stupidity and single-digit combat power, so how can they transform into heroes and fight against the super-villainous villains who are intent on destroying the world? How can they turn into heroes and fight against the super baddest villains intent on destroying the world? The "King Bomb" brothers, who look like grown-ups but have minds like no other, will save the future on behalf of the K-Star!',
        popularity: 566.779,
        poster_path: "/nZQPbD7IEKWiUDK7s9GKHwqP88g.jpg",
        release_date: "2024-07-18",
        title: "Escape from the 21st Century",
        video: false,
        vote_average: 9.5,
        vote_count: 2,
      },
      {
        adult: false,
        backdrop_path: "/wsgni4E1UnBuvFouUUanSdniQi0.jpg",
        genre_ids: [28, 12, 18],
        id: 718821,
        original_language: "en",
        original_title: "Twisters",
        overview:
          "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
        popularity: 476.421,
        poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
        release_date: "2024-07-10",
        title: "Twisters",
        video: false,
        vote_average: 7.171,
        vote_count: 289,
      },
      {
        adult: false,
        backdrop_path: "/adAJDB2Au3x5ve2YyWaEYy4EUw.jpg",
        genre_ids: [18, 10749, 35],
        id: 1191610,
        original_language: "es",
        original_title: "Goyo",
        overview:
          "A young autistic museum guide lives by a strict routine — until he falls in love with his coworker and must confront a whirlwind of new, intense emotions.",
        popularity: 350.206,
        poster_path: "/fCjC1RRbEJUpDjM55RNUMXQen0b.jpg",
        release_date: "2024-06-27",
        title: "Goyo",
        video: false,
        vote_average: 6.798,
        vote_count: 42,
      },
      {
        adult: false,
        backdrop_path: "/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg",
        genre_ids: [16, 28, 18],
        id: 1104844,
        original_language: "ja",
        original_title: "劇場版ブルーロック -EPISODE 凪-",
        overview:
          "One day, Nagi Seishiro receives an invitation to the mysterious BLUE LOCK Project. What awaits him there is an encounter with the finest strikers assembled from across the country. Nagi's dream of becoming the best, alongside Mikage Reo, will take this prodigy to a world he's never known.",
        popularity: 462.384,
        poster_path: "/ae434jM5NG2kKX1rRkG5giMhpPI.jpg",
        release_date: "2024-04-19",
        title: "BLUE LOCK THE MOVIE -EPISODE NAGI-",
        video: false,
        vote_average: 8.37,
        vote_count: 23,
      },
      {
        adult: false,
        backdrop_path: "/uNTciMXpCQDg7gvgMsPCdnxo6Re.jpg",
        genre_ids: [28, 53],
        id: 1114738,
        original_language: "en",
        original_title: "Boneyard",
        overview:
          'After Police Chief Carter discovers the remains of eleven women, FBI Special Agent Petrovick is recruited to profile the serial killer responsible for the infamous "boneyard" killings. As the police force, narcotics agency, and FBI lock horns, a tangled web of intrigue turns everyone into a suspect.',
        popularity: 272.809,
        poster_path: "/xkNK36hQv8SWiwiQoE7naRfP0zL.jpg",
        release_date: "2024-07-05",
        title: "Boneyard",
        video: false,
        vote_average: 5.7,
        vote_count: 46,
      },
      {
        adult: false,
        backdrop_path: "/psheU3eQROaYZ0HCbZ0QdbqsiWq.jpg",
        genre_ids: [10749, 878, 18],
        id: 914206,
        original_language: "fr",
        original_title: "La Bête",
        overview:
          "In the near future where emotions have become a threat, Gabrielle finally decides to purify her DNA in a machine that will immerse her in her past lives and rid her of any strong feelings. She then meets Louis and feels a powerful connection, as if she had known him forever.",
        popularity: 277.007,
        poster_path: "/o42BrPukzRXlDi9KBCdClNqhlEr.jpg",
        release_date: "2024-02-07",
        title: "The Beast",
        video: false,
        vote_average: 6.299,
        vote_count: 72,
      },
      {
        adult: false,
        backdrop_path: "/buawWBeKYjYfeiPoS2jIcjOrghZ.jpg",
        genre_ids: [27, 53],
        id: 1214509,
        original_language: "en",
        original_title: "In a Violent Nature",
        overview:
          "The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.",
        popularity: 276.13,
        poster_path: "/ndXBFfs5lufT4tuNvroqrraajBf.jpg",
        release_date: "2024-05-31",
        title: "In a Violent Nature",
        video: false,
        vote_average: 5.853,
        vote_count: 129,
      },
      {
        adult: false,
        backdrop_path: "/Ahn9zBmRImn0uJ17IuQugjywQZB.jpg",
        genre_ids: [12, 10751],
        id: 959098,
        original_language: "fr",
        original_title: "Le Dernier Jaguar",
        overview:
          "Grown up in the Amazon rainforest, Autumn lives with Hope, the cute baby jaguar she adopted. However, a circumstance forces Autumn to return to New York. Autumn goes back into the jungle to save Hope from grave danger.",
        popularity: 268.741,
        poster_path: "/ocHu00nOZzK0m9BsFdrFg3SglS0.jpg",
        release_date: "2024-02-01",
        title: "Autumn and the Black Jaguar",
        video: false,
        vote_average: 5.667,
        vote_count: 33,
      },
      {
        adult: false,
        backdrop_path: "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
        genre_ids: [28, 36],
        id: 1311550,
        original_language: "en",
        original_title: "House of Ga'a",
        overview:
          "At the height of the Oyo Empire, the ferocious Bashorun Ga'a became more powerful than the kings he enthroned, only to be undone by his own blood.",
        popularity: 359.493,
        poster_path: "/s9CBq3jjJvFtLCrvDquoj1kIz0c.jpg",
        release_date: "2024-07-26",
        title: "House of Ga'a",
        video: false,
        vote_average: 4.889,
        vote_count: 9,
      },
    ],
    total_pages: 168,
    total_results: 3356,
  },
];
